set(CMAKE_INSTALL_BINDIR "executables")
set(CMAKE_INSTALL_SBINDIR "executables")
set(CMAKE_INSTALL_LIBEXECDIR "executables")
set(CMAKE_INSTALL_LIBDIR "libraries")
set(CMAKE_INSTALL_INCLUDEDIR "include")
set(CMAKE_INSTALL_OLDINCLUDEDIR "include")

# SHAREDSTATEDIR
# LOCALSTATEDIR
# RUNSTATEDIR
# DATAROOTDIR
# DATADIR
# INFODIR
# LOCALEDIR
# MANDIR
# DOCDIR

set(CMAKE_INSTALL_LIBRARY_RUNTIME_DESTINATION "${CMAKE_INSTALL_LIBDIR}")
set(CMAKE_INSTALL_PACKAGE_DESTINATION "package")

set(CMAKE_DEBUG_POSTFIX "_debug")

set(CMAKE_STATIC_LIBRARY_PREFIX "")
set(CMAKE_SHARED_LIBRARY_PREFIX "")
